import time
import random
import os
import glob
import sys
try:
    from instagrapi import Client
except ImportError:
    print("Dependency missing. Run: pip install instagrapi")
    exit()

print("==========================================")
print("    🚀 API-BASED AUTO FOLLOW ENGINE 🚀    ")
print("       [HEADLESS — NO BROWSER WINDOW]     ")
print("==========================================\n")

cl = Client()

print("Select authentication method:")
print("[1]. Username + Password (supports 2FA via SMS or authenticator app)")
print("[2]. Inject SessionID directly (bypasses login flow)")
login_choice = input("\nChoice (1 or 2): ").strip()

if login_choice == '1':
    username = input("Enter Instagram username: ")
    password = input("Enter Instagram password: ")

    try:
        print("\n[⏳] Connecting to Instagram API server...")
        cl.login(username, password)
        print("=> ✅ AUTHENTICATION SUCCESSFUL!")
    except Exception as e:
        error_msg = str(e)
        if "Two-factor authentication required" in error_msg or "verification_code" in error_msg:
            print("\n=> 🔐 Two-Factor Authentication detected. A verification code was sent to your device.")
            code = input("Enter the 6-digit OTP (from SMS or Google Authenticator): ")
            try:
                cl.login(username, password, verification_code=code)
                print("=> ✅ 2FA BYPASSED SUCCESSFULLY!")
            except Exception as e2:
                print(f"=> ❌ OTP LOGIN FAILED: {e2}")
                exit()
        else:
            print(f"=> ❌ LOGIN FAILED (checkpoint triggered or wrong credentials): {e}")
            exit()
else:
    print("\n[GUIDE]: Copy the 'sessionid' cookie value from your browser's DevTools > Application > Cookies.")
    session_id = input("\nPaste your Chrome SessionID here: ").strip()
    try:
        print("\n[⏳] Injecting session cookie...")
        cl.login_by_sessionid(session_id)
        print("=> ✅ SESSION INJECTION SUCCESSFUL! Starting follow operations...")
    except Exception as e:
        print(f"=> ❌ SESSION EXPIRED OR REJECTED BY INSTAGRAM: {e}")
        exit()

# Auto-locate the most recent clean session file generated by 2.js
session_files = glob.glob("session_follow*.txt")
if not session_files:
    print("❌ No session file found (session_follow_...txt). Run 2.js first to generate a clean target list.")
    exit()

latest_session = max(session_files, key=os.path.getctime)
print(f"\n=> 📁 Located session file: {latest_session}")

with open(latest_session, "r", encoding="utf-8") as f:
    users = [u.strip() for u in f.readlines() if u.strip()]

print(f"   + Total clean IDs ready for execution: {len(users)}\n")

delay_min = int(input("Enter MINIMUM rest interval between each follow in seconds (e.g. 5): "))
delay_max = int(input("Enter MAXIMUM rest interval in seconds (e.g. 15): "))

print("\n🚀 STARTING API FOLLOW SESSION...\n")

for target_user in users:
    try:
        # Instagram API requires numeric user ID — resolve from username before calling follow
        user_id = cl.user_id_from_username(target_user)
        
        # Fire the follow request directly to Meta's API endpoint
        result = cl.user_follow(user_id)
        
        if result:
            print(f"=> ✅ API FOLLOW SUCCESS: @{target_user}")
            with open("ig_done.txt", "a", encoding="utf-8") as f:
                f.write(target_user + "\n")
        else:
            print(f"=> ⏩ Skipped @{target_user} (silently rejected by server)")
            with open("ig_done.txt", "a", encoding="utf-8") as f:
                f.write(target_user + "\n")
                
    except Exception as e:
        error_msg = str(e)
        if "429" in error_msg or "RetryError" in error_msg or "too many" in error_msg.lower():
            print(f"\n=> ⛔ ⛔ RATE LIMIT WARNING: BLOCKED BY INSTAGRAM (HTTP 429)!")
            print(f"      - Your IP has exceeded the API request threshold.")
            print(f"      - Stop the tool and wait 30–60 minutes before resuming.")
            break
        else:
            print(f"=> ❌ API ERROR @{target_user}: Account not found or inaccessible ({error_msg[:50]}...)")
            with open("ig_done.txt", "a", encoding="utf-8") as f:
                f.write(target_user + "\n")

    sleep_time = random.randint(delay_min, delay_max)
    print(f"  (Masking API access pattern — sleeping {sleep_time}s...)")
    time.sleep(sleep_time)

print("\n=> 🎉 SESSION COMPLETE — ALL TARGETS PROCESSED!")
